server:
  #ssl:
    # The path to the key store that holds the SSL certificate (a jks or p12 file).
    #key-store: classpath:keystore.p12
    # The password used to access the key store.
    #key-store-password: 1992Andres_
    # The type of the key store.
    #key-store-type: "PKCS12"
    # The password used to access the key in the key store.

  # The port this server is listening on
  #port: 8443
  port: 8080
spring:
  application:
    name: Stockify  
  data:
    mongodb:
        uri: mongodb+srv://Andres:1992Andres_@cluster0.zfyx6.mongodb.net/test?retryWrites=true&w=majority
        database: test
logging:
   level:
     org.springframework.data.couchbase.repository.query: DEBUG